server {
  listen 80;

  # Servir Vite build
  location / {
    root   /usr/share/nginx/html;
    index  index.html;
    try_files $uri /index.html;
  }

  # Proxy al backend
  location /api {
    proxy_pass http://backend:5000; # nombre del servicio en docker-compose
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
