# Archivo principal de docker-compose.
# Version 1.1.0
# Author EXACTUM-dev

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_CLERK_PUBLISHABLE_KEY: ${VITE_CLERK_PUBLISHABLE_KEY}
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - .env
