name: Frontend CI
on:
  push:
    paths:
      - "frontend/**"
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install --prefix frontend
      - run: npm test --prefix frontend
